[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run build && ls -la dist/']

[start]
cmd = 'npx serve dist -s -l 4173 -H 0.0.0.0'

[variables]
NODE_ENV = 'production'
PORT = '4173'